services:
  - type: web
    name: frontend-winter-2023-group-project
    env: static
    buildCommand: cd ui; npm install; npm build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend-winter-2023-group-project
    env: node
    buildCommand: cd api; npm install
    startCommand: cd api; npm start
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database-winter-2023-group-project
    databaseName: trivia_db
    ipAllowList: [] # only allow internal connections
